sudo: required
services:
  - docker

before_install:
  - docker build -t shivamanipatil/test-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shivamanipatil/test-react yarn test -- --coverage