sudo: required
services:
  - docker

before_install:
  - docker build -t shivamanipatil/test-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shivamanipatil/test-react yarn test
  
deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "test-react"
  env: "TestReact-env"
  bucket_name: elasticbeanstalk-us-east-2-566702853041
  bucket_path: "test-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY